import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./styles/globals.css";
import { roboto as robotoVariable } from "./styles";


const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto" satisfies typeof robotoVariable,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
